apiVersion: batch/v1
kind: Job
metadata:
  name: vlmrm
  labels:
    kueue.x-k8s.io/queue-name: preemptable-batch
spec:
  template:
    metadata:
      name: vlmrm-pod
    spec:
      containers:
        - name: vlmrm-container
          image: rocamonde/vlmrm:latest
          env:
            - name: WANDB_API_KEY
              value: "YOUR_WANDB_API_KEY_HERE"
            - name: NCCL_SHM_DISABLE
              value: "1"
          command: ["python3", "-m", "vlmrm.cli.train"]
          args:
            - |
              {
                "env_name": "Humanoid-v4",
                "base_path": "/data/runs/training",
                "seed": 42,
                "description": "Humanoid kneeling",
                "tags": [
                  "kneeling",
                  "humanoid",
                  "clip",
                  "model-scaling"
                ],
                "reward": {
                  "name": "clip",
                  "pretrained_model": "ViT-bigG-14/laion2b_s39b_b160k",
                  "batch_size": 3200,
                  "alpha": 0.0,
                  "target_prompts": ["a humanoid robot kneeling"],
                  "baseline_prompts": ["a humanoid robot"],
                  "cache_dir": "/data/cache",
                  "camera_config": {
                      "trackbodyid": 1,
                      "distance": 3.5,
                      "lookat": [0.0, 0.0, 1.0],
                      "elevation": -10.0,
                      "azimuth": 180.0
                  }
                },
                "rl": {
                  "policy_name": "MlpPolicy",
                  "n_steps": 10000000,
                  "n_envs_per_worker": 8,
                  "episode_length": 100,
                  "learning_starts": 50000,
                  "train_freq": 100,
                  "batch_size": 512,
                  "gradient_steps": 100,
                  "tau": 0.005,
                  "gamma": 0.95,
                  "learning_rate": 6e-4
                },
                "logging": {
                  "checkpoint_freq": 128000,
                  "video_freq": 128000
                }
              }
          resources:
            requests:
              cpu: 32
              memory: "128Gi"
              nvidia.com/gpu: 4
            limits:
              cpu: 64
              memory: "256Gi"
              nvidia.com/gpu: 4
          volumeMounts:
            - name: vlmrm-volume
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: vlmrm-volume
          persistentVolumeClaim:
            claimName: vlmrm-storage
