env_name: MountainCarContinuous-v0
base_path: data/runs/training
seed: 91
description: Mountain car continuous
tags:
  - mountain car
  - clip
reward:
  name: clip
  pretrained_model: ViT-bigG-14/laion2b_s39b_b160k
  batch_size: 1600
  alpha: 0.8
  target_prompts:
    - a red car at the mountain peak next to the yellow flag
  baseline_prompts:
    - a red car at the bottom of the valley
  cache_dir: .cache
  # Stuff below added on top of VLMRM
  embed_type: "avg_frame"
  reward_type: "projection"
  window_size: 1
  window_step: 1
rl:
  policy_name: MlpPolicy
  n_steps: 3000000
  n_envs_per_worker: 8
  episode_length: 200
  learning_starts: 600
  train_freq: 200
  batch_size: 512
  gradient_steps: 200
  tau: 0.01
  gamma: 0.9999
  learning_rate: 3e-4
  ent_coef: 0.1
  use_sde: true
  policy_kwargs:
    log_std_init: -3.67
    net_arch:
      - 64
      - 64
logging:
  checkpoint_freq: 128000
  video_freq: 64000